service: auth-server

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  timeout: 60

environment:
  CLIENT_ID: 142127699156-gmvmvnd32dso2nokccchd3ugb4ohoba1.apps.googleusercontent.com
  CLIENT_SECRET: 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
  PROJECT_ID: meet-app-334009
  CALENDAR_ID: fullstackwebdev@careerfoundry.com
functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
